### ISSUE TITLE
Separate java 8 codecs to a separated module

### ISSUE THREAD

**Issue by AdrianRaFo** [47degrees/helios#126]
We want to separate the Encoders and Decoders of java time types on a separate module in order to keep the java 7 compatibility in the core module.

**Comment by b0n541** [comment]
I would like to take on that issue.

**Comment by b0n541** [comment]
I have some problems to setup the project in my IDE. There are NullPointerExceptions thrown during the inital Gradle setup in module helio-dsl-schema and helio-meta.

Which JDK should be  used?
